"""Initial schema

Revision ID: 03f1bb924a82
Revises: 
Create Date: 2026-06-05 21:15:15.784765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f1bb924a82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_servicio')
    )
    op.create_table('plan_suscripcion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_plan', sa.String(length=50), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limite_usuarios', sa.Integer(), nullable=False),
    sa.Column('porcentaje_retencion_base', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('organizacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('plan_suscripcion_id', sa.UUID(), nullable=True),
    sa.Column('fecha_vencimiento_plan', sa.DateTime(), nullable=True),
    sa.Column('estado_pago_suscripcion', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_suscripcion_id'], ['plan_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('configuracion_kpi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tiempo_respuesta_maximo_minutos', sa.Integer(), nullable=False),
    sa.Column('meta_ingresos_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meta_servicios_completados', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conductor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('licencia', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('taller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=150), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('taller_especialidad',
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('taller_id', 'especialidad_id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('estado_disponible', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('incidente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('estado_actual', sa.String(length=30), nullable=False),
    sa.Column('tipo_problema', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('direccion_referencia', sa.String(length=255), nullable=True),
    sa.Column('solicitado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('asignado_en', sa.DateTime(), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(), nullable=True),
    sa.Column('conductor_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=True),
    sa.Column('tecnico_id', sa.UUID(), nullable=True),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('organizacion_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('creado_offline', sa.Boolean(), nullable=False),
    sa.Column('fecha_sincronizacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductor.id'], ),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('diagnostico_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('probabilidad_falla', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confianza', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('analizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencia_multimedia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('cargado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_incidente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cambiado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('cambiado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cambiado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_ruta_tecnico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('registrado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidad_incidente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('precio_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eta_minutos', sa.Integer(), nullable=True),
    sa.Column('ofrecida_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('respondida_en', sa.DateTime(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('incidente_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_pasarela', sa.String(length=50), nullable=True),
    sa.Column('token_pago_externo', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    op.create_table('comision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_comision', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_neto_taller', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquidada', sa.Boolean(), nullable=False),
    sa.Column('calculada_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaccion_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transaccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaccion_id')
    )
    op.create_table('comprobante',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('url_pdf', sa.String(length=500), nullable=True),
    sa.Column('emitido_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaccion_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaccion_id'], ['transaccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero'),
    sa.UniqueConstraint('transaccion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobante')
    op.drop_table('comision')
    op.drop_table('transaccion')
    op.drop_table('oportunidad_incidente')
    op.drop_table('historial_ruta_tecnico')
    op.drop_table('historial_incidente')
    op.drop_table('evidencia_multimedia')
    op.drop_table('diagnostico_ia')
    op.drop_table('incidente')
    op.drop_table('vehiculo')
    op.drop_table('tecnico')
    op.drop_table('taller_especialidad')
    op.drop_table('taller')
    op.drop_table('sesion')
    op.drop_table('conductor')
    op.drop_table('bitacora')
    op.drop_table('usuario')
    op.drop_table('configuracion_kpi')
    op.drop_table('organizacion')
    op.drop_table('rol')
    op.drop_table('plan_suscripcion')
    op.drop_table('especialidad')
    # ### end Alembic commands ###
